sudo: required
dist: trusty

language: python
# well its really octave, but that is not supported

matrix:
  include:
    - python: "2.7"
      env: SYMPY_VER=0.7.6 OCT_PPA=no DOCTEST=no
    - python: "2.7"
      env: SYMPY_VER=0.7.6 OCT_PPA=yes DOCTEST=yes COLUMNS=80
    - python: "3.4"
      env: SYMPY_VER=0.7.6.1 OCT_PPA=yes DOCTEST=yes COLUMNS=80
    - python: "2.7"
      env: SYMPY_VER=1.0 OCT_PPA=yes DOCTEST=yes COLUMNS=80
    - python: "3.5"
      env: SYMPY_VER=1.0 OCT_PPA=yes DOCTEST=yes COLUMNS=80

# need octave devel pkgs for doctest (has compiled code as of July 2015)
# TODO: once doctest is in OF, change to "install -forge" below
install:
  - if [ "x$OCT_PPA" = "xyes" ]; then
        sudo apt-add-repository -y ppa:octave/stable;
    fi
  - sudo apt-get update -qq -y;
  - sudo apt-get install -qq -y octave liboctave-dev;
  - "pip install sympy==$SYMPY_VER"
  - #if [ "x$DOCTEST" = "xyes" ]; then
    #    octave -W --no-gui --eval "pkg install -forge doctest";
    #fi
  - # Or for a specific doctest version:
    if [ "x$DOCTEST" = "xyes" ]; then
        wget https://github.com/catch22/octave-doctest/releases/download/v0.4.1/doctest-0.4.1.tar.gz;
        octave -W --no-gui --eval "pkg install doctest-0.4.1.tar.gz";
    fi

# all commands here must have exit code 0 for the build to be called "passing"
# debugging: octave -W --no-gui --eval "syms x; A = [x sin(x) x^3]; A; exit(0)"
script:
  - octave -W --no-gui --eval "ver; pwd; exit(0)"
  - stty cols 80 rows 40
  - tput cols; stty size
  - pushd src; make; popd
  - pushd inst
  - octave -W --no-gui --eval "r = octsympy_tests; exit(r)"
  - cat octsympy_tests.log
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave -W --no-gui --eval "pkg load doctest; syms x; r = doctest('.'); exit(~r)";
    fi
  - popd

#after_script:
#  - echo ${TRAVIS_TEST_RESULT}
