language: python
# well its really octave, but that is not supported

matrix:
  include:
    - python: "2.7"
      env: SYMPY_VER=0.7.5 DOCTEST=no
    - python: "2.7"
      env: SYMPY_VER=0.7.6 DOCTEST=yes
    - python: "3.4"
      env: SYMPY_VER=0.7.6.1 DOCTEST=yes

# need octave devel pkgs for doctest (has compiled code as of July 2015)
# TODO: once doctest is in OF, change to "install -forge" below
install:
  - sudo apt-add-repository --yes ppa:octave/stable
  - sudo apt-get update
  - sudo apt-get install octave liboctave-dev
  - "pip install sympy==$SYMPY_VER"
  - wget https://github.com/catch22/octave-doctest/releases/download/v0.4.0/doctest-0.4.0.tar.gz
  - octave --eval "pkg install doctest-0.4.0.tar.gz"

# all commands here must have exit code 0 for the build to be called "passing"
# debugging: octave --eval "syms x; A = [x sin(x) x^3]; A; exit(0)"
script:
  - octave --eval "ver; pwd; exit(0)"
  - pushd src; make; popd
  - pushd inst
  - octave --eval "r = octsympy_tests; exit(r)"
  - cat octsympy_tests.log
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave --eval "pkg load doctest; syms x; r = doctest('.'); exit(~r)";
    fi
  - popd

#after_script:
#  - echo ${TRAVIS_TEST_RESULT}
